repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev:  v0.1.23
    hooks:
      - id: terraform-fmt
      - id: gofmt
      - id: tflint
        args:
         - --minimum-failure-severity=error