name: Automatic CI for TFE Modules

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  terraform_format:

    name: Run terraform fmt
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Format all .tf files recursively
      run: |
        terraform fmt -check -diff -recursive ${{ github.workspace }}
  terraform_lint:

    name: Run terraform-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Setup Terraform Lint
      uses: terraform-linters/setup-tflint@v1
      with:
        tflint_version: v0.34.1

    - name: Terraform Init
      id: init
      run: |
        terraform init

    - name: Lint root module
      run: |
        tflint --config ${{ github.workspace }}/.tflint.hcl ${{ github.workspace }}
    - name: Lint collector-dashboards directory in a loop
      run: |
        for m in $(ls -1d collector-dashboards/*/)
        do
          tflint \
            --config ${{ github.workspace }}/.tflint.hcl \
            ${{ github.workspace }}/${m}
        done
    - name: Lint examples directory in a loop
      run: |
        for m in $(ls -1d examples/*/)
        do
          tflint \
            --config ${{ github.workspace }}/.tflint.hcl \
            ${{ github.workspace }}/${m}
        done
